name: Build ISO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt -y install build-essential mtools xorriso grub-common squashfs-tools
    
    - name: Build
      run: ./fetch_build
      
    - name: Create output folder
      run: mkdir out
      
    - name: Move ISO to the output folder
      run: mv ubuntu-vanilla-gnome-22.04.1-amd64.iso out
      
    - name: Move md5 checksum to the output folder
      run: mv ubuntu-vanilla-gnome-22.04.1-amd64.iso.md5sum out
      
    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
          name: ubuntu-vanilla-gnome-22.04.1-amd64
          path: out
