name: Build ISO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt -y install build-essential mtools xorriso grub-common squashfs-tools
    
    - name: Build
      run: ./fetch_build
      
    - name: Create output folder
      run: mkdir out
      
    - name: Move ISO to the output folder
      run: mv ubuntu-desnap-vanilla-gnome-22.04.iso out
      
    - name: Move md5 checksum to the output folder
      run: mv ubuntu-desnap-vanilla-gnome-22.04.iso.md5sum out
      
    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
          name: ubuntu-desnap-vanilla-gnome-22.04
          path: out
          
    - name: Release file
      # You may pin to the exact commit or the version.
      # uses: djnicholson/release-action@e9a535b3eced09c460e07a84118fb74ae9b53236
      uses: djnicholson/release-action@v2.10
      with:
        # GitHub auth token
        token: ${{ secrets.FP_TOKEN }}
        # Name for the asset
        asset-name: ubuntu-desnap-vanilla-gnome-22.04.iso
        # File to release
        file: ubuntu-desnap-vanilla-gnome-22.04.iso
